### PR TITLE
tmux grouped session support and a bug fix

### PR DESCRIPTION
**Pull request by glikely**
Hi Dustin,

I've been using byobu for many years now, but the default behavour of tmux (all clients see the same view) is not useful for me. I did have an extra script that would force grouped sessions, but it was pretty ugly. I finally got around to implementing it properly within byobu, which is the first commit in this pull request.

The second commit is a simple bug fix to make the argument list include the command name when calling os.execvp() so that it shows up correctly when listing processes.

Cheers,
g.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Tested this for 5 seconds, works fine on freebsd :+1: :+1: :+1:

**Comment by glikely** [comment]
I found a few bugs in my python code when I tried to build the Debian package. This third commit fixes them.

**Comment by dustinkirkland** [comment]
Hey Grant!

Thanks so much for the patch.  I can understand the point of view, that sometimes multiple different users, ssh'ing into a single system, and landing in the same Byobu session isn't ideal.  Do you know that there's a hot key to create a separate session?  Ctrl-Shift-F2 will create a new session, and then you can use Alt-Up and Alt-Down to move among sessions.  Disconnect, and when you ssh back in, you'll be prompted with the select-session prompt.

Generally speaking, Byobu is really about "sharing".  The default mode of Byobu, sharing the same session, is the appropriate default, I believe.  I see people every day using Byobu to "pair program" from their own home-offices, around the globe.  So I really don't want to change that default.

But I am happy to make that configurable.  Perhaps a per user environment variable in their profile. "BYOBU_SESSION_SHARED=1" is the default, easily changed to BYOBU_SESSION_SHARED=0, to have the behavior you desire, Grant?

**Comment by dustinkirkland** [comment]
Commit 2 looks good, I've pulled that one in already.

**Comment by glikely** [comment]
Hi Dustin, comments below...

On Mon, Jun 27, 2016 at 9:39 PM, Dustin Kirkland
<notifications@github.com> wrote:
>
> Hey Grant!
>
> Thanks so much for the patch. I can understand the point of view, that sometimes multiple different users, ssh'ing into a single system, and landing in the same Byobu session isn't ideal. Do you know that there's a hot key to create a separate session? Ctrl-Shift-F2 will create a new session, and then you can use Alt-Up and Alt-Down to move among sessions. Disconnect, and when you ssh back in, you'll be prompted with the select-session prompt.

That's not /quite/ the same thing. I still want to be sharing the same
session: I want to see the same window list at the bottom of every
client terminal, and be able to switch between them freely. The
difference is I need a way for the viewport of each terminal to be
independent.

I've got byobu set to run as my shell whenever I open a terminal, and
I typically have multiple terminal open. With byobu-screen, each
terminal connects to the same session. Switching windows in one
terminal doesn't change the view on another, but with byobu-tmux it
does. Every terminal changes in lockstep, which isn't so useful when
having multiple terminals side-by-side.  :-)

> Generally speaking, Byobu is really about "sharing". The default mode of Byobu, sharing the same session, is the appropriate default, I believe. I see people every day using Byobu to "pair program" from their own home-offices, around the globe. So I really don't want to change that default.

I understand concern about changing defaults, so I'm not going to
argue strongly for that. I think it would be valuable for -screen and
-tmux backends to have the same behaviour as much as possible, but I
won't push the point.

> But I am happy to make that configurable. Perhaps a per user environment variable in their profile. "BYOBU_SESSION_SHARED=1" is the default, easily changed to BYOBU_SESSION_SHARED=0, to have the behavior you desire, Grant?

Yes, I would be okay with that.

g.

**Comment by dustinkirkland** [comment]
Okay, let me try out your patch and the new behavior here for a couple of days...

**Comment by dustinkirkland** [comment]
Okay, I'm merging this in, and releasing it with byobu 5.109, and uploading to Ubuntu yakkety now.  Thanks, Grant!

**Comment by glikely** [comment]
Thanks Dustin

g.

**Pull request closed without merging**
